export const userTypes = {
    SIGN_UP_SUCCESS: "  SIGN_UP_SUCESS",
    SIGN_UP_FAIL: " SIGN_UP_FAIL",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: " SIGN_IN_FAIL",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    LOG_OUT_FAIL: "LOG_OUT_FAIL",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
    LOAD_USER_FAILURE: "LOAD_USER_FAILURE"
}