export const PostTypes = {

    GET_POSTS: "GET_POSTS",
    GET_POST: "GET_POST",
    POST_ERROR: "POST_ERROR",
    UPDATE_LIKES: "UPDATE_LIKES",
    DELETE_POST: "DELETE_POST",
    ADD_POST: "ADD_POST",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT"

};